name: Deploy API to Somee via FTP

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore Finedu.Auth.sln

      - name: Build
        run: dotnet build Finedu.Auth.sln -c Release --no-restore

      - name: Publish for IIS (includes web.config)
        run: >
          dotnet publish ./Finedu.Auth/Finedu.Auth.csproj
          -c Release
          -o ./publish
          -p:PublishIISAssets=true

      # === Firebase Admin: escribir el JSON desde el secret ===
      - name: Write Firebase service account to ./publish/secrets/serviceAccountKey.json
        shell: pwsh
        run: |
          $secretJson = @'
          ${{ secrets.FIREBASE_KEY }}
          '@
          $dir = Join-Path $PWD "publish/secrets"
          New-Item -ItemType Directory -Force -Path $dir | Out-Null
          $path = Join-Path $dir "serviceAccountKey.json"
          $secretJson | Out-File -FilePath $path -Encoding utf8 -Force
          Write-Host "Firebase key written to $path"

      # Comprobación: el archivo existe y es JSON válido
      - name: Validate firebase key file
        shell: pwsh
        run: |
          $path = Join-Path $PWD "publish/secrets/serviceAccountKey.json"
          if (!(Test-Path $path)) { throw "serviceAccountKey.json not found" }
          try { $null = Get-Content $path | ConvertFrom-Json } catch { throw "FIREBASE_KEY is not valid JSON" }
          Write-Host "serviceAccountKey.json exists and is valid JSON."

      # (Opcional) Preflight FTP
      - name: FTP preflight check
        shell: bash
        run: |
          curl -v --disable-epsv --ftp-pasv \
            ftp://fineduauth.somee.com \
            --user 'cid919310uttt1:Cid919310$' || true

      # === Deploy a Somee por FTP ===
      - name: Deploy to Somee via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: fineduauth.somee.com      # solo el host
          username: cid919310uttt1
          password: Cid919310$
          protocol: ftp
          port: 21
          local-dir: ./publish/
          server-dir: /www.fineduauth.somee.com/
          exclude: |
            **/.git*
            **/.github/**
          dangerous-clean-slate: false
