name: Deploy API to Somee via FTP

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore Finedu.Auth.sln

      - name: Build
        run: dotnet build Finedu.Auth.sln -c Release --no-restore

      - name: Publish for IIS (includes web.config)
        run: >
          dotnet publish ./Finedu.Auth/Finedu.Auth.csproj
          -c Release
          -o ./publish
          -p:PublishIISAssets=true

      # 1) Escribir la credencial de Firebase (desde el Secret) como archivo en ./publish
      - name: Write Firebase service account (FIREBASE_KEY) to file
        shell: pwsh
        run: |
          $path = Join-Path $PWD "publish/firebase-key.json"
          '${{ secrets.FIREBASE_KEY }}' | Out-File -FilePath $path -Encoding utf8 -Force

      # 2) Inyectar GOOGLE_APPLICATION_CREDENTIALS en web.config (IIS)
      - name: Inject GOOGLE_APPLICATION_CREDENTIALS into web.config
        shell: pwsh
        run: |
          $webConfigPath = Join-Path $PWD "publish/web.config"
          if (!(Test-Path $webConfigPath)) {
            Write-Error "web.config not found at $webConfigPath. Ensure -p:PublishIISAssets=true"
          }
          [xml]$xml = Get-Content $webConfigPath
          $asp = $xml.configuration.'system.webServer'.aspNetCore
          if (-not $asp) { Throw "aspNetCore element not found in web.config" }

          if (-not $asp.environmentVariables) {
            $envNode = $xml.CreateElement("environmentVariables")
            [void]$asp.AppendChild($envNode)
          } else {
            $envNode = $asp.environmentVariables
          }

          $existing = $envNode.SelectNodes("add") | Where-Object { $_.name -eq 'GOOGLE_APPLICATION_CREDENTIALS' }
          if ($existing) {
            $existing.value = ".\firebase-key.json"
          } else {
            $add = $xml.CreateElement("add")
            $add.SetAttribute("name", "GOOGLE_APPLICATION_CREDENTIALS")
            $add.SetAttribute("value", ".\firebase-key.json")
            [void]$envNode.AppendChild($add)
          }

          $xml.Save($webConfigPath)
          Write-Host "Injected GOOGLE_APPLICATION_CREDENTIALS into web.config"

      # (Opcional) Prueba rápida de conexión FTP
      - name: FTP preflight check
        shell: bash
        run: |
          curl -v --disable-epsv --ftp-pasv \
            ftp://fineduauth.somee.com \
            --user 'cid919310uttt1:Cid919310$' || true

      # 3) Deploy a Somee
      - name: Deploy to Somee via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # SOLO el host, sin 'ftp://'
          server: fineduauth.somee.com
          username: cid919310uttt1
          password: Cid919310$
          protocol: ftp
          port: 21
          local-dir: ./publish/
          server-dir: /www.fineduauth.somee.com/
          exclude: |
            **/.git*
            **/.github/**
          dangerous-clean-slate: false
